### ISSUE TITLE
bro

### ISSUE THREAD

**Issue by AverseABFun** [TheTIW/UV-Static#24]
![image](https://github.com/TheTIW/UV-Static/assets/81586710/958a80a9-1c60-4a33-8d41-6714ec4605f1)

ULTRAVIOLET SUPPORTS STATIC WEBSITES NATIVELY

**Comment by KwazyMotoo** [comment]
old project, as you can see, its archived. notice how nobody cares? go touch grass, theres more to life. also most of this entire thing was made by NCGAMING under the TIW name, so your targeting the wrong people.

**Comment by AverseABFun** [comment]
thanks for that tasty tidbit of information of the main person being NCGAMING >:)

**Comment by AverseABFun** [comment]
although thats in the readme

**Comment by AverseABFun** [comment]
but at any rate it isn't archived
