### ISSUE TITLE
TypeError: Failed to Fetch

### ISSUE THREAD

**Issue by PHYT90DitYT** [TheTIW/UV-Static#3]
The title contains the error that occurred when I deployed to Netlify, turned it on, and then tried to access Google.com.
![image](https://github.com/TheTIW/UV-Static/assets/136361545/97b0fac0-6265-495f-8ea1-890a52d394b7)

**Comment by trentonk23** [comment]
ME TOOOOOOO!!!!!!!!!

**Comment by PHYT90DitYT** [comment]
PLEASE FIX THIS ERROR

**Comment by teamapolloreal** [comment]
its cuz they use a blocked site as their domain, im trying to fix it on "UVS-Reborn" idk if i can tho 💀

**Comment by PHYT90DitYT** [comment]
OK, I'll wait.

**Comment by Thesecondalthowcool** [comment]
No. it's because the bare server their using is broken. If you need a proxy, just use https://iloveschoollunch.pages.dev/

**Comment by KwazyMotoo** [comment]
fixed it.
