### ISSUE TITLE
this still uses bare, its not a static website.

### ISSUE THREAD

**Issue by desplmfao** [TheTIW/UV-Static#6]

**Comment by KwazyMotoo** [comment]
no shit, its just an easy, deployable way to run uv, and its faster. You can make a site EASILY. so just shut up.

**Comment by desplmfao** [comment]
> run uv, and its faster. You can make a site EASIL

its not "faster" you are just running your own bare server over the shit and claiming its "the first EVER static uv" when it very clearly isnt

**Comment by desplmfao** [comment]
and a fun fact, the first ever version of uv was hosted on github pages and used the incog.dev bare server

**Comment by AverseABFun** [comment]
![image](https://github.com/TheTIW/UV-Static/assets/81586710/958a80a9-1c60-4a33-8d41-6714ec4605f1)

extra ammo for you
